Algoritmo "7"
//A loja Mamão com Açúcar está vendendo seus produtos em 5 (cinco) prestações sem juros. Faça um algoritmo que
//receba um valor de uma compra e mostre o valor das prestações.
var

valor : real

inicio

escreval("Digite o valor da compra que deseja fazer em nosso estabelecimento: ")
leia(valor)
escreval("O valor desse produto será dividido em 5 prestações de: ", (valor/5))

fimalgoritmo