Algoritmo "2"

//Escreva um algoritmo para determinar o consumo médio de um automóvel sendo fornecida a distância total
//percorrida pelo automóvel e o total de combustível gasto

var

distancia, gasolina : real

inicio

escreval("Digite quantos KM foram percorridos: ")
leia(distancia)
escreval("Digite quantos litros de gasolina foram consumidos: ")
leia(gasolina)

escreval("O consumo médio em km/l de seu automóvel é: ", (distancia / gasolina))

fimalgoritmo